### PR TITLE
Add microphone streaming with VAD to sample scene 2

### PR DESCRIPTION
**Pull request by Rossbrownzzz**
This is my first pull request on a public repo so if I mess something up in the process please don't hesitate to correct.

This is a functional demo, it adds a checkbox to the microphone scene to enable streaming audio transcription.

Some issues I know of right now and am working on fixing:
high pass filter not yet implemented
stopping the recording can sometimes be too fast or too slow, I plan to rework VAD loop conditions to get better results

image

### CODE REVIEW

**Comment by Macoron** [comment]
Hey @Rossbrownzzz, thank you for your contribution. Ping me when you will be ready for review.

**Comment by Macoron** [comment]
@Rossbrownzzz are you coming back to this? I can continue your PR if you want to

**Comment by Rossbrownzzz** [comment]
hey @Macoron I've moved streaming to a new scene to work on so that scene 2 doesn't need changed since the code was getting pretty messy handling both streaming and manual recording in the same scene. I am pretty comfortable with how streaming is working right now if you wanted to review it.

**Comment by Macoron** [comment]
Checked your PR. On first glance VAD looks okay, but handling microphone input and mixing with previous transcription is not that good.

I will probably make chunk-based microphone and sliding-window transcription myself. After that, we can merge your VAD in it.

**Comment by Macoron** [comment]
@Rossbrownzzz so I finally managed to put streaming together. Check latest master and this PR #40. 

I left TODO comment where to include VAD that you've made - would be great if you port it into new streaming class.

**Comment by Rossbrownzzz** [comment]
It's a holiday here so it will be a couple of days before I'm able to get back to this - but I will take a look when I am!

**Comment by Rossbrownzzz** [comment]
hey @Macoron the streaming looks great! I was a little confused on what you envisioned for the VAD for this example scene though. You have a [comment](https://github.com/Macoron/whisper.unity/blob/master/Packages/com.whisper.unity/Runtime/WhisperStream.cs#L243) for implementing VAD but it is after getting the text from the buffer.
From what I can see in [whisper.cpp](https://github.com/ggerganov/whisper.cpp/blob/master/examples/stream/stream.cpp#L274) in their stream example they use vad to see if they should get audio. What I had in my head seems more like the [talk](https://github.com/ggerganov/whisper.cpp/blob/master/examples/talk/talk.cpp) example now that I think about it more closely. More along the lines of no buttons, VAD determines when you start and stop speaking.

Just curious what you had in mind for it so I can make sure I'm thinking about this the same way you are.

**Comment by Macoron** [comment]
@Rossbrownzzz  So my idea was inspired by original implementation of `stream` from whisper.cpp. Let's say we have this example with two sentences:

Screenshot 2023-07-07 at 08 40 36

We starting moving to the right by `StepSamples` and recurrently do transcription:

image

Now VAD shows us that there is no speech and two things happens:
1. We clear `_oldBuffer` and use current transcription as a prompt for next iterations (place where I left comment). It is called "new line" in whisper.cpp implementation
2. Whisper goes into "sleep mode" and skip audio until user starts speaking again.

After VAD detects speech, it starts transcribing again by new segmet.

image

Of course I'm skipping some details, like VAD thresholds, etc.

What do you think about this design?

**Comment by Rossbrownzzz** [comment]
Yep, that makes sense to me, I'll see what I can put together!

**Comment by thizzhead** [comment]
Is there any progress on this. I've tried converting it myself with a mixed result. I do have something that seems to work, but the accuracy of the model seems to have dropped significantly as a result.

**Comment by Macoron** [comment]
@Rossbrownzzz are you coming back to this?

**Comment by Rossbrownzzz** [comment]
Similar to you @thizzhead I got it to work sometimes but it's pretty timing dependent what I have right now. My main issue was with trying to use the buffer for VAD. I'm not sure if it's just because of the sample rate of the microphone or not but every other update the old buffer had too few samples to really work with [https://github.com/Macoron/whisper.unity/blob/master/Packages/com.whisper.unity/Runtime/WhisperStream.cs#L269](here is where it updates.)
I'm in the process of moving to a new apartment right now so I haven't had as much time as I would like lately for personal projects. I can hopefully give more details on what I've tried soon.

**Comment by Macoron** [comment]
> Similar to you @thizzhead I got it to work sometimes but it's pretty timing dependent what I have right now. My main issue was with trying to use the buffer for VAD. I'm not sure if it's just because of the sample rate of the microphone or not but every other update the old buffer had too few samples to really work with [https://github.com/Macoron/whisper.unity/blob/master/Packages/com.whisper.unity/Runtime/WhisperStream.cs#L269](here is where it updates.) I'm in the process of moving to a new apartment right now so I haven't had as much time as I would like lately for personal projects. I can hopefully give more details on what I've tried soon.

Alright, I see. I will take a look at VAD implementation. Maybe your original idea of using it more for command like scenario was better.

Anyway, thank you for your contribution.

**Comment by Macoron** [comment]
@Rossbrownzzz @thizzhead I decided to make it step by step. Right now I ported VAD in #44 and moved it to the microphone sample without streaming. Feel free to check if it works on your setup.

After that, I will try to do add VAD into streaming.

**Pull request closed without merging**
